In [ ]:
import pandas as pd

# Omogućavanje prikaza svih stupaca
pd.set_option('display.max_columns', None)

# Učitavanje podataka iz CSV datoteke
PATH = "C:/Users/Pc/Desktop/6_semestar/SRP/Koraci/Checkpoint_1/synthetic_fraud_dataset.csv"

# Učitavanje svih redova
data = pd.read_csv(PATH, delimiter=',')

# Učitavanje prvih 2000 redova
data1 = pd.read_csv(PATH, delimiter=',', nrows=2000)

# Ispis prvih 5 redova
print(data1.head())

  Transaction_ID    User_ID  Transaction_Amount Transaction_Type  \
0      TXN_33553  USER_1834               39.79              POS
1       TXN_9427  USER_7875                1.19    Bank Transfer
2        TXN_199  USER_2734               28.96           Online
3      TXN_12447  USER_2617              254.32   ATM Withdrawal
4      TXN_39489  USER_2014               31.28              POS

             Timestamp  Account_Balance Device_Type  Location  \
0  2023-08-14 19:30:00         93213.17      Laptop    Sydney
1  2023-06-07 04:01:00         75725.25      Mobile  New York
2  2023-06-20 15:25:00          1588.96      Tablet    Mumbai
3  2023-12-07 00:31:00         76807.20      Tablet  New York
4  2023-11-11 23:44:00         92354.66      Mobile    Mumbai

  Merchant_Category  IP_Address_Flag  Previous_Fraudulent_Activity  \
0            Travel                0                             0
1          Clothing                0                             0
2       Restaurants                0                             0
3          Clothing                0                             0
4       Electronics                0                             1

   Daily_Transaction_Count  Avg_Transaction_Amount_7d  \
0                        7                     437.63
1                       13                     478.76
2                       14                      50.01
3                        8                     182.48
4                       14                     328.69

   Failed_Transaction_Count_7d   Card_Type  Card_Age  Transaction_Distance  \
0                            3        Amex        65                883.17
1                            4  Mastercard       186               2203.36
2                            4        Visa       226               1909.29
3                            4        Visa        76               1311.86
4                            4  Mastercard       140                966.98

  Authentication_Method  Risk_Score  Is_Weekend  Fraud_Label
0             Biometric      0.8494           0            0
1              Password      0.0959           0            1
2             Biometric      0.8400           0            1
3                   OTP      0.7935           0            1
4              Password      0.3819           1            1

In [5]:
# Ispis dimenzija skupa podataka
print(data.shape)

(50000, 21)

In [6]:
# Ispis imena stupaca i nedostajućih vrijednosti
print(data.isna().sum())

Transaction_ID                  0
User_ID                         0
Transaction_Amount              0
Transaction_Type                0
Timestamp                       0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
IP_Address_Flag                 0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Avg_Transaction_Amount_7d       0
Failed_Transaction_Count_7d     0
Card_Type                       0
Card_Age                        0
Transaction_Distance            0
Authentication_Method           0
Risk_Score                      0
Is_Weekend                      0
Fraud_Label                     0
dtype: int64

In [7]:
# Ispis broja jedinstvenih vrijednosti po stupcima
print(data.nunique())

Transaction_ID                  50000
User_ID                          8963
Transaction_Amount              21763
Transaction_Type                    4
Timestamp                       47724
Account_Balance                 49867
Device_Type                         3
Location                            5
Merchant_Category                   5
IP_Address_Flag                     2
Previous_Fraudulent_Activity        2
Daily_Transaction_Count            14
Avg_Transaction_Amount_7d       31420
Failed_Transaction_Count_7d         5
Card_Type                           4
Card_Age                          239
Transaction_Distance            47546
Authentication_Method               4
Risk_Score                       9931
Is_Weekend                          2
Fraud_Label                         2
dtype: int64

In [ ]:
# Ispis tipova podataka po stupcima (analiza kvantitativnih i kvalitativnih varijabli)
print(data.dtypes)

Transaction_ID                   object
User_ID                          object
Transaction_Amount              float64
Transaction_Type                 object
Timestamp                        object
Account_Balance                 float64
Device_Type                      object
Location                         object
Merchant_Category                object
IP_Address_Flag                   int64
Previous_Fraudulent_Activity      int64
Daily_Transaction_Count           int64
Avg_Transaction_Amount_7d       float64
Failed_Transaction_Count_7d       int64
Card_Type                        object
Card_Age                          int64
Transaction_Distance            float64
Authentication_Method            object
Risk_Score                      float64
Is_Weekend                        int64
Fraud_Label                       int64
dtype: object

In [10]:
# Ispis broja jedinstvenih vrijednosti po stupcima
for column in data:
    print(data[column].value_counts())
    input("...")

Transaction_ID
TXN_5311     1
TXN_37819    1
TXN_39188    1
TXN_17568    1
TXN_19769    1
            ..
TXN_39489    1
TXN_12447    1
TXN_199      1
TXN_9427     1
TXN_33553    1
Name: count, Length: 50000, dtype: int64
User_ID
USER_6599    16
USER_9998    16
USER_3925    16
USER_3415    15
USER_5014    15
             ..
USER_4000     1
USER_1501     1
USER_5657     1
USER_8613     1
USER_5580     1
Name: count, Length: 8963, dtype: int64
Transaction_Amount
7.65      14
8.74      13
0.24      13
18.58     12
6.50      12
          ..
258.79     1
342.27     1
225.31     1
90.01      1
58.78      1
Name: count, Length: 21763, dtype: int64
Transaction_Type
POS               12549
Online            12546
ATM Withdrawal    12453
Bank Transfer     12452
Name: count, dtype: int64
Timestamp
2023-06-04 06:35:00    4
2023-02-05 17:52:00    3
2023-03-10 19:11:00    3
2023-02-13 19:47:00    3
2023-10-03 15:19:00    3
                      ..
2023-01-29 18:38:00    1
2023-05-09 08:55:00    1
2023-01-30 19:32:00    1
2023-03-09 19:47:00    1
2023-06-05 20:55:00    1
Name: count, Length: 47724, dtype: int64
Account_Balance
90794.73    2
57855.62    2
96487.32    2
56653.17    2
70162.77    2
           ..
76960.11    1
28791.75    1
29916.41    1
67895.67    1
76807.20    1
Name: count, Length: 49867, dtype: int64
Device_Type
Tablet    16779
Mobile    16640
Laptop    16581
Name: count, dtype: int64
Location
Tokyo       10208
Mumbai       9994
London       9945
Sydney       9938
New York     9915
Name: count, dtype: int64
Merchant_Category
Clothing       10033
Groceries      10019
Travel         10015
Restaurants     9976
Electronics     9957
Name: count, dtype: int64
IP_Address_Flag
0    47490
1     2510
Name: count, dtype: int64
Previous_Fraudulent_Activity
0    45080
1     4920
Name: count, dtype: int64
Daily_Transaction_Count
3     3634
10    3623
11    3620
4     3606
2     3605
1     3598
12    3586
5     3582
7     3574
14    3571
9     3538
13    3524
6     3521
8     3418
Name: count, dtype: int64
Avg_Transaction_Amount_7d
384.72    7
82.26     7
226.40    7
454.19    6
422.33    6
         ..
365.43    1
10.09     1
427.44    1
380.83    1
16.07     1
Name: count, Length: 31420, dtype: int64
Failed_Transaction_Count_7d
3    10216
0    10014
4     9954
1     9919
2     9897
Name: count, dtype: int64
Card_Type
Mastercard    12693
Visa          12560
Amex          12419
Discover      12328
Name: count, dtype: int64
Card_Age
80     247
31     244
84     243
63     239
55     239
      ...
9      180
69     178
181    175
188    169
156    167
Name: count, Length: 239, dtype: int64
Transaction_Distance
1743.63    4
951.92     4
127.17     3
507.33     3
3048.71    3
          ..
2768.44    1
999.06     1
330.48     1
1923.21    1
4436.61    1
Name: count, Length: 47546, dtype: int64
Authentication_Method
Biometric    12591
PIN          12586
Password     12457
OTP          12366
Name: count, dtype: int64
Risk_Score
0.6917    16
0.3606    15
0.2990    15
0.9781    14
0.2228    14
          ..
0.4741     1
0.5626     1
0.3965     1
0.9968     1
0.3527     1
Name: count, Length: 9931, dtype: int64
Is_Weekend
0    35018
1    14982
Name: count, dtype: int64
Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

In [9]:
# Ispis imena stupaca
print(data.columns.values)

['Transaction_ID' 'User_ID' 'Transaction_Amount' 'Transaction_Type'
 'Timestamp' 'Account_Balance' 'Device_Type' 'Location'
 'Merchant_Category' 'IP_Address_Flag' 'Previous_Fraudulent_Activity'
 'Daily_Transaction_Count' 'Avg_Transaction_Amount_7d'
 'Failed_Transaction_Count_7d' 'Card_Type' 'Card_Age'
 'Transaction_Distance' 'Authentication_Method' 'Risk_Score' 'Is_Weekend'
 'Fraud_Label']